//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sporty.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exercise
    {
        public Exercise()
        {
            this.Attachment = new HashSet<Attachment>();
            this.MaterialPerExercise = new HashSet<MaterialPerExercise>();
        }
    
        public Nullable<System.Guid> UserId { get; set; }
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<System.TimeSpan> Duration { get; set; }
        public Nullable<double> Distance { get; set; }
        public System.DateTime Date { get; set; }
        public int SportTypeId { get; set; }
        public Nullable<int> Heartrate { get; set; }
        public Nullable<int> TrainingTypeId { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public Nullable<double> Speed { get; set; }
        public Nullable<int> HeartrateMax { get; set; }
        public Nullable<double> SpeedMax { get; set; }
        public Nullable<int> Trimp { get; set; }
        public Nullable<int> Cadence { get; set; }
        public Nullable<int> CadenceMax { get; set; }
        public Nullable<double> Elevation { get; set; }
        public string WeatherNote { get; set; }
        public string WeatherCondition { get; set; }
        public Nullable<double> Temperature { get; set; }
    
        public virtual ICollection<Attachment> Attachment { get; set; }
        public virtual SportType SportType { get; set; }
        public virtual TrainingType TrainingType { get; set; }
        public virtual User User { get; set; }
        public virtual Zone Zone { get; set; }
        public virtual ICollection<MaterialPerExercise> MaterialPerExercise { get; set; }
    }
}
