//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sporty.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.MaterialPerExercise = new HashSet<MaterialPerExercise>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool InUsage { get; set; }
        public string Description { get; set; }
        public Nullable<int> Lifetime { get; set; }
        public string Filename { get; set; }
        public System.Guid UserId { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<MaterialPerExercise> MaterialPerExercise { get; set; }
    }
}
