//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sporty.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metrics
    {
        public int Id { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<int> RestingPulse { get; set; }
        public Nullable<double> SleepDuration { get; set; }
        public Nullable<short> SleepQuality { get; set; }
        public Nullable<short> StressLevel { get; set; }
        public Nullable<short> Motivation { get; set; }
        public Nullable<short> Mood { get; set; }
        public Nullable<short> Sick { get; set; }
        public string Description { get; set; }
        public Nullable<short> YesterdaysTraining { get; set; }
    
        public virtual User User { get; set; }
    }
}
