//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sporty.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SportyEntities : DbContext
    {
        public SportyEntities()
            : base("name=SportyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Application> Application { get; set; }
        public DbSet<Attachment> Attachment { get; set; }
        public DbSet<Exercise> Exercise { get; set; }
        public DbSet<Goal> Goal { get; set; }
        public DbSet<Material> Material { get; set; }
        public DbSet<MaterialPerExercise> MaterialPerExercise { get; set; }
        public DbSet<Metrics> Metrics { get; set; }
        public DbSet<Phase> Phase { get; set; }
        public DbSet<Plan> Plan { get; set; }
        public DbSet<Profile> Profile { get; set; }
        public DbSet<SportType> SportType { get; set; }
        public DbSet<TrainingType> TrainingType { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<WeekPlan> WeekPlan { get; set; }
        public DbSet<Zone> Zone { get; set; }
    }
}
