//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sporty.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phase
    {
        public Phase()
        {
            this.WeekPlan = new HashSet<WeekPlan>();
        }
    
        public int Id { get; set; }
        public System.Guid UserId { get; set; }
        public string ShortName { get; set; }
        public string Description { get; set; }
        public string Color { get; set; }
        public Nullable<int> Order { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<WeekPlan> WeekPlan { get; set; }
    }
}
