//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sporty.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan
    {
        public int Id { get; set; }
        public System.Guid UserId { get; set; }
        public Nullable<System.TimeSpan> Duration { get; set; }
        public int SportTypeId { get; set; }
        public int ZoneId { get; set; }
        public string Description { get; set; }
        public Nullable<double> Distance { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> TrainingTypeId { get; set; }
        public bool IsFavorite { get; set; }
    
        public virtual SportType SportType { get; set; }
        public virtual TrainingType TrainingType { get; set; }
        public virtual User User { get; set; }
        public virtual Zone Zone { get; set; }
    }
}
