//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sporty.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public System.Guid ProfileId { get; set; }
        public Nullable<bool> IsMale { get; set; }
        public Nullable<double> BodyHeight { get; set; }
        public string Culture { get; set; }
        public System.Guid UserId { get; set; }
        public Nullable<int> MaxHeartrate { get; set; }
        public Nullable<System.TimeSpan> DailyMetricsMailSendingTime { get; set; }
    
        public virtual User User { get; set; }
    }
}
