//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sporty.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Exercise = new HashSet<Exercise>();
            this.Goal = new HashSet<Goal>();
            this.Material = new HashSet<Material>();
            this.Metrics = new HashSet<Metrics>();
            this.Phase = new HashSet<Phase>();
            this.Plan = new HashSet<Plan>();
            this.Profile = new HashSet<Profile>();
            this.SportType = new HashSet<SportType>();
            this.TrainingType = new HashSet<TrainingType>();
            this.WeekPlan = new HashSet<WeekPlan>();
            this.Zone = new HashSet<Zone>();
        }
    
        public System.Guid ApplicationId { get; set; }
        public System.Guid UserId { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public int PasswordFormat { get; set; }
        public string PasswordSalt { get; set; }
        public string Email { get; set; }
        public string LoweredEmail { get; set; }
        public bool IsApproved { get; set; }
        public bool IsLockedOut { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastLoginDate { get; set; }
        public System.DateTime LastPasswordChangedDate { get; set; }
        public System.DateTime LastLockoutDate { get; set; }
        public int FailedPasswordAttemptCount { get; set; }
        public System.DateTime FailedPasswordAttemptWindowStart { get; set; }
        public int FailedPasswordAnswerAttemptCount { get; set; }
        public System.DateTime FailedPasswordAnswerAttemptWindowStart { get; set; }
        public string Comment { get; set; }
        public Nullable<System.Guid> ActivationCode { get; set; }
        public string SsoToken { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual ICollection<Exercise> Exercise { get; set; }
        public virtual ICollection<Goal> Goal { get; set; }
        public virtual ICollection<Material> Material { get; set; }
        public virtual ICollection<Metrics> Metrics { get; set; }
        public virtual ICollection<Phase> Phase { get; set; }
        public virtual ICollection<Plan> Plan { get; set; }
        public virtual ICollection<Profile> Profile { get; set; }
        public virtual ICollection<SportType> SportType { get; set; }
        public virtual ICollection<TrainingType> TrainingType { get; set; }
        public virtual ICollection<WeekPlan> WeekPlan { get; set; }
        public virtual ICollection<Zone> Zone { get; set; }
    }
}
