//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sporty.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeekPlan
    {
        public int Id { get; set; }
        public System.Guid UserId { get; set; }
        public int WeekNumber { get; set; }
        public int Year { get; set; }
        public int PhaseId { get; set; }
    
        public virtual Phase Phase { get; set; }
        public virtual User User { get; set; }
    }
}
